import type { Tag, CampaignCategory } from './types';

export const CAMPAIGN_CATEGORIES: CampaignCategory[] = [
  '언어',
  'FE',
  'BE',
  'DB',
  '클라우드',
  '모바일',
  '기타',
];

export const AVAILABLE_TAGS: Tag[] = [
  // 언어
  { id: 1, name: 'JavaScript', category: '언어' },
  { id: 2, name: 'TypeScript', category: '언어' },
  { id: 3, name: 'Python', category: '언어' },
  { id: 4, name: 'Java', category: '언어' },
  { id: 5, name: 'Go', category: '언어' },
  { id: 6, name: 'Rust', category: '언어' },
  { id: 7, name: 'C++', category: '언어' },
  { id: 8, name: 'C#', category: '언어' },
  { id: 9, name: 'Kotlin', category: '언어' },
  { id: 10, name: 'Swift', category: '언어' },
  { id: 11, name: 'PHP', category: '언어' },
  { id: 12, name: 'Ruby', category: '언어' },

  // FE
  { id: 13, name: 'React', category: 'FE' },
  { id: 14, name: 'Vue', category: 'FE' },
  { id: 15, name: 'Angular', category: 'FE' },
  { id: 16, name: 'Svelte', category: 'FE' },
  { id: 17, name: 'NextJS', category: 'FE' },
  { id: 18, name: 'Nuxt', category: 'FE' },
  { id: 19, name: 'Remix', category: 'FE' },
  { id: 20, name: 'Astro', category: 'FE' },
  { id: 21, name: 'SolidJS', category: 'FE' },
  { id: 22, name: 'Preact', category: 'FE' },
  { id: 23, name: 'Qwik', category: 'FE' },
  { id: 91, name: 'Redux', category: 'FE' },
  { id: 92, name: 'Zustand', category: 'FE' },
  { id: 93, name: 'Recoil', category: 'FE' },
  { id: 94, name: 'Jotai', category: 'FE' },
  { id: 95, name: 'MobX', category: 'FE' },
  { id: 96, name: 'React Query', category: 'FE' },
  { id: 97, name: 'SWR', category: 'FE' },
  { id: 110, name: 'Tailwind CSS', category: 'FE' },
  { id: 111, name: 'Sass', category: 'FE' },
  { id: 112, name: 'CSS', category: 'FE' },
  { id: 113, name: 'HTML', category: 'FE' },

  // BE
  { id: 24, name: 'NestJS', category: 'BE' },
  { id: 25, name: 'Express', category: 'BE' },
  { id: 26, name: 'Fastify', category: 'BE' },
  { id: 27, name: 'Koa', category: 'BE' },
  { id: 28, name: 'Spring', category: 'BE' },
  { id: 29, name: 'Spring Boot', category: 'BE' },
  { id: 30, name: 'Django', category: 'BE' },
  { id: 31, name: 'Flask', category: 'BE' },
  { id: 32, name: 'FastAPI', category: 'BE' },
  { id: 33, name: 'Rails', category: 'BE' },
  { id: 34, name: 'Laravel', category: 'BE' },
  { id: 35, name: 'ASP.NET', category: 'BE' },
  { id: 36, name: 'Gin', category: 'BE' },
  { id: 37, name: 'Fiber', category: 'BE' },
  { id: 107, name: 'Node.js', category: 'BE' },
  { id: 108, name: 'Deno', category: 'BE' },
  { id: 109, name: 'Bun', category: 'BE' },

  // DB
  { id: 38, name: 'MySQL', category: 'DB' },
  { id: 39, name: 'PostgreSQL', category: 'DB' },
  { id: 40, name: 'MongoDB', category: 'DB' },
  { id: 41, name: 'Redis', category: 'DB' },
  { id: 42, name: 'Elasticsearch', category: 'DB' },
  { id: 43, name: 'Cassandra', category: 'DB' },
  { id: 44, name: 'DynamoDB', category: 'DB' },
  { id: 45, name: 'SQLite', category: 'DB' },
  { id: 46, name: 'MariaDB', category: 'DB' },
  { id: 47, name: 'Oracle', category: 'DB' },
  { id: 48, name: 'SQL Server', category: 'DB' },
  { id: 49, name: 'SQL', category: 'DB' },

  // 클라우드
  { id: 50, name: 'Docker', category: '클라우드' },
  { id: 51, name: 'Kubernetes', category: '클라우드' },
  { id: 52, name: 'AWS', category: '클라우드' },
  { id: 53, name: 'GCP', category: '클라우드' },
  { id: 54, name: 'Azure', category: '클라우드' },
  { id: 55, name: 'Jenkins', category: '클라우드' },
  { id: 56, name: 'GitHub Actions', category: '클라우드' },
  { id: 57, name: 'GitLab CI', category: '클라우드' },
  { id: 58, name: 'CircleCI', category: '클라우드' },
  { id: 59, name: 'Terraform', category: '클라우드' },
  { id: 60, name: 'Ansible', category: '클라우드' },
  { id: 61, name: 'Nginx', category: '클라우드' },
  { id: 62, name: 'Apache', category: '클라우드' },

  // 모바일
  { id: 98, name: 'React Native', category: '모바일' },
  { id: 99, name: 'Flutter', category: '모바일' },
  { id: 100, name: 'Electron', category: '모바일' },
  { id: 101, name: 'Tauri', category: '모바일' },

  // 기타
  { id: 63, name: 'Git', category: '기타' },
  { id: 64, name: 'GitHub', category: '기타' },
  { id: 65, name: 'GitLab', category: '기타' },
  { id: 66, name: 'Bitbucket', category: '기타' },
  { id: 67, name: 'npm', category: '기타' },
  { id: 68, name: 'Yarn', category: '기타' },
  { id: 69, name: 'pnpm', category: '기타' },
  { id: 70, name: 'Webpack', category: '기타' },
  { id: 71, name: 'Vite', category: '기타' },
  { id: 72, name: 'Rollup', category: '기타' },
  { id: 73, name: 'esbuild', category: '기타' },
  { id: 74, name: 'Babel', category: '기타' },
  { id: 75, name: 'ESLint', category: '기타' },
  { id: 76, name: 'Prettier', category: '기타' },
  { id: 77, name: 'REST', category: '기타' },
  { id: 78, name: 'GraphQL', category: '기타' },
  { id: 79, name: 'gRPC', category: '기타' },
  { id: 80, name: 'WebSocket', category: '기타' },
  { id: 81, name: 'tRPC', category: '기타' },
  { id: 82, name: 'Swagger', category: '기타' },
  { id: 83, name: 'Postman', category: '기타' },
  { id: 84, name: 'Jest', category: '기타' },
  { id: 85, name: 'Vitest', category: '기타' },
  { id: 86, name: 'Cypress', category: '기타' },
  { id: 87, name: 'Playwright', category: '기타' },
  { id: 88, name: 'Selenium', category: '기타' },
  { id: 89, name: 'JUnit', category: '기타' },
  { id: 90, name: 'Pytest', category: '기타' },
  { id: 102, name: 'AI', category: '기타' },
  { id: 103, name: 'Machine Learning', category: '기타' },
  { id: 104, name: 'TensorFlow', category: '기타' },
  { id: 105, name: 'PyTorch', category: '기타' },
  { id: 106, name: 'OpenAI', category: '기타' },
  { id: 114, name: 'WebAssembly', category: '기타' },
  { id: 115, name: 'Blockchain', category: '기타' },
];

export const getTagsByCategory = (category: CampaignCategory): Tag[] => {
  return AVAILABLE_TAGS.filter((tag) => tag.category === category);
};

export const MAX_SELECTED_TAGS = 3;

export const DEFAULT_ENGAGEMENT_SCORE = 70;
